BEJ: Beijing   # 北京
SHA: Shanghai  # 上海
CAN: Guangzhou # 广州
SZX: Shenzhen  # 深圳
CTU: Chengdu   # 成都
HGH: Hangzhou  # 杭州
NKG: Nanjing   # 南京
XIY: Xian      # 西安
CKG: Chongqing # 重庆
WUH: Wuhan     # 武汉
DLC: Dalian    # 大连
TAO: Taian     # 泰安
TSN: Tianjin   # 天津
HRB: Harbin    # 哈尔滨
SHE: Shenyang  # 沈阳
FOC: Foshan    # 佛山
XMN: Xiamen    # 厦门
CSX: Changsha  # 长沙
KMG: Kunming   # 昆明
NNG: Nanning   # 南宁
URC: Urumqi    # 乌鲁木齐
HET: Hohhot    # 呼和浩特
TYN: Taiyuan   # 太原
JNZ: Jinzhou   # 锦州
YNT: Yantai    # 烟台
WEH: Weihai    # 威海
YIW: Yiwu      # 义乌
LHW: Lanzhou   # 兰州
XUZ: Xuzhou    # 徐州
JGN: Jiayuguan # 嘉峪关
LZH: Luzhou    # 泸州
YIC: Yichun    # 宜春
JIQ: Qianjiang # 黔江
LZY: Linzhi    # 林芝
SYM: Shenyang  # 沈阳
KHN: Nanchang  # 南昌
CGQ: Changchun # 长春
TNA: Jinan     # 济南
SJW: Shijiazhuang # 石家庄
HFE: Hefei     # 合肥
NGB: Ningbo    # 宁波
FUG: Fuzhou    # 福州
ZQZ: Zhangjiakou # 张家口
YCU: Yuncheng  # 运城
LYA: Luoyang   # 洛阳
INC: Yinchuan  # 银川
JMU: Jiamusi   # 佳木斯
MDG: Mudanjiang # 牡丹江
HSN: Zhoushan  # 舟山
JGS: Jinggangshan # 井冈山
