# 酒店名称字典配置
# Hotel Names Dictionary Configuration

hotel_names:
  - "HILTON SYDNEY"
  - "SHERATON MELBOURNE"
  - "MARRIOTT BRISBANE"
  - "HYATT PERTH"
  - "INTERCONTINENTAL ADELAIDE"
  - "RADISSON DARWIN"
  - "NOVOTEL CAIRNS"
  - "PULLMAN CANBERRA"
  - "WESTIN SYDNEY"
  - "DOUBLETREE MELBOURNE"
  - "SOFITEL GOLD COAST"
  - "GRAND HYATT SYDNEY"
  - "PARK HYATT MELBOURNE"
  - "FOUR SEASONS SYDNEY"
  - "SHANGRI-LA SYDNEY"
  - "MANDARIN ORIENTAL SYDNEY"
  - "RITZ CARLTON MELBOURNE"
  - "ST REGIS MELBOURNE"
  - "WALDORF ASTORIA SYDNEY"
  - "CONRAD SYDNEY"

city_names:
  - "SYDNEY"
  - "MELBOURNE"
  - "BRISBANE"
  - "PERTH"
  - "ADELAIDE"
  - "DARWIN"
  - "CAIRNS"
  - "CANBERRA"
  - "GOLD COAST"
  - "HOBART"
  - "TOWNSVILLE"
  - "BALLARAT"
  - "BENDIGO"
  - "GEELONG"
  - "TOOWOOMBA"
  - "LAUNCESTON"
  - "ROCKHAMPTON"
  - "BUNBURY"
  - "BUNDABERG"
  - "WAGGA WAGGA"
