# IATA代码字典配置(aliyun数据库取的50条数据)
XJC
ETC
SEH
ETD
ETH
ETN
ETS
ETV
EUH
EUK
EUP
EUT
EVA
EVE
EVR
EWG
EXA
EXH
EXJ
EXL
EXN
EXS
EXT
EXU
EXV
EXW
EXY
EXZ
EZB
EZD
EZE
EZR
EZS
EZY
E2_
E6_
FAB
FAD
FAH
FAJ
FAM
FAO
FAR
FAS
FAT
FAW
FBU
FCA
FCB
FCK
FCN
FCP
FCR
FCV
FDA
FDB
FDE
FDO
FDR
FDS
FDX
FDY
FE_
FEA
FEG
FEI
FEM
FEX
FF_
FFD
FFF
FFG
FFI
FFM
FFP
FFT
FFV
FGG
FGN
FGS
FHE
FHM
FHS
FHY
FIA
FIE
FIF
FII
FIN
FIX
FJC
FJI
FJS
FK_
FKI
FKS
FLC
FLG
FLI
FLJ
FLM
FLT
FLU
FLX
FLY
FLZ
FN_
FNA
FNC
FNG
FNM
FNO
FNT
FNV
FOB
FOM
FOO
FOR
FPC
FPG
FPO
FPR
FPY
FQ_
FRA
FRC
FRD
FRE
FRG
FRJ
FRR
FS_
FSC
FSD
FSR
FST
FSW
FT_
FTA
FTL
FTR
FTY
FTZ
FUA
FUJ
FUP
FWA
FWD
FWI
FWL
FXI
FXR
FXT
FXX
FYE
FYG
GTA
GTI
GTV
GTY
GU_
GUM
GUN
GUY
GVN
EWG
GWY
GYM
GZ_
GZA
GZD
GZP
G8_
HAG
HAK
HAL
HAN
HAT
HAU
HAX
HB_
HBH
HBI
HC_
HCP
HDA
HDC
HDI
HDR
HEA
HEB
HEC
HEL
HEM
HER
HET
HF_
HFR
HFY
HGH
HH_
HHA
HHE
HHH
HHI
HHK
HHN
HHO
HI_
HIB
HIT
HJ_
HJA
HJT
HK_
HKA
HKE
HKG
HKI
HKN
HKR
HKS
HLC
HLG
HLI
HLK
HLQ
HLR
HLU
HLW
HLZ
HMA
HMF
HMR
HMS
HMX
HON
HOP
HOR
HPJ
HPL
HPO
HPR
HPT
HRT
HSE
HSI
HSK
HSS
HSU
HSW
HSY
HTA
HTG
HTH
HUM
HVN
HVY
HW_
HWY
HXA
HYH
HYR
HYS
HZT
H0_
H1_
H3_
H5_
IAA
IAC
IAD
IAM
IAR
IAW
IAX
IAY
IAZ
IBB
IBC
IBE
IBK
IBL
IBS
IBT
IBX
IBZ
ICA
ICC
ICE
ICG
ICL
IDA
IDE
IDR
IEP
IFA
IFS
IFT
IGO
IHE
IIG
IIL
IJ_
IJA
IKA
IKR
IL_
ILL
IME
IMR
IMT
IMX
INC
ING
INJ
INL
INV
INX
IO_
IOS
IPC
IRA
IRB
IRC
IRG
IRI
IRK
IRL
IRM
IRO
IRP
IRQ
IRR
IRS
IRX
IRZ
ISA
ISC
ISD
ISG
ISL
ISM
ISR
ISV
ISW
ITN
ITY
IUS
IVE
IWD
IWY
IYE
IZA
IZG
IZM
I2_
I3_
I5_
I7_
I8_
JAC
JAF
JAG
JAI
JAL
JAR
JAT
JAV
JAZ
JBA
JBR
JBU
JCB
JCC
JCI
JCK
JCS
JCT
JCX
JDP
JEA
JEF
JEJ
JEK
JEL
JEM
JET
JEX
JFK
JFL
JFU
JGD
JGO
JI_
JIA
JJA
JJP
JKK
JLE
JLN
JMA
JME
JMS
JMX
JNA
JO_
JOC
JON
JOS
JOY
JPQ
JPT
JRF
JRN
JST
JTA
JTE
JTM
JTR
JTT
JTU
JTV
JUB
JUC
JUS
JX_
JXX
JYH
JZA
J9_
J0_
J5_
J7_
KAC
KAD
KAE
KAI
KAJ
KAL
KAM
KAO
KAP
KAT
KAV
KAW
KBA
KBV
KDC
KDZ
KEE
KEM
KEN
KFA
KFC
KFK
KFL
KFR
KFS
KGA
KGL
KGO
KHB
KHM
KHO
KHV
KHY
KIL
KIS
KJC
KKK
KLC
KLD
KLG
KLM
KLO
KLS
KM_
KMA
KMC
KME
KMF
KMG
KMI
KMP
KMV
KNA
XY_
KNM
KNS
KNX
KOP
KOR
KPH
KQA
KRB
KRE
KRG
KRM
KRP