# 旅客姓名字典配置
# Traveller Names Dictionary Configuration
traveller_names:
- "ZHANG/WEI"
- "WANG/FANG"
- "LI/NA"
- "ZHAO/LEI"
- "CHEN/MING"
- "LIU/JING"
- "YANG/YANG"
- "HUANG/LEI"
- "WU/JING"
- "ZHOU/MING"
- "XU/FANG"
- "SUN/LEI"
- "MA/JING"
- "ZHU/MING"
- "HU/FANG"
- "GUO/LEI"
- "LIN/JING"
- "HE/MING"
- "GAO/FANG"
- "LIANG/LEI"
- "SONG/JING"
- "TANG/MING"
- "FENG/FANG"
- "HAN/LEI"
- "CAO/JING"
- "DENG/MING"
- "PENG/FANG"
- "CUI/LEI"
- "YU/JING"
- "LU/MING"
- "JIANG/FANG"
- "DING/LEI"
- "WEI/JING"
- "PAN/MING"
- "REN/FANG"
- "JOHN/SMITH"
- "MARY/JOHNSON"
- "JAMES/BROWN"
- "PATRICIA/JONES"
- "ROBERT/GARCIA"
- "JENNIFER/MILLER"
- "MICHAEL/DAVIS"
- "LINDA/RODRIGUEZ"
- "WILLIAM/WILSON"
- "ELIZABETH/MARTINEZ"
- "DAVID/ANDERSON"
- "BARBARA/TAYLOR"
- "RICHARD/THOMAS"
- "SUSAN/HERNANDEZ"
- "JOSEPH/MOORE"
- "QUENTIN/WU"
- "MULI/XI"
